// Especialidades sugeridas por oficio. Se usan en el onboarding y edición de
// perfil profesional para que el profesional declare en qué se especializa.
// No son buscables ni indexadas: son información descriptiva visible en el
// perfil público, debajo del nombre de cada oficio.
// Clave = nombre exacto del oficio tal como aparece en el seed.

export const TRADE_SPECIALTIES: Record<string, string[]> = {
  // Construcción
  Albañilería: [
    "Mampostería",
    "Revoque exterior",
    "Revoque interior",
    "Contrapisos",
    "Construcción de galpones",
    "Ladrillo visto",
  ],
  Pintura: [
    "Interior",
    "Exterior",
    "Barniz y lustre",
    "Spray",
    "Pinturas decorativas",
    "Texturas",
  ],
  "Yesería y revoque": [
    "Revoque fino",
    "Revoque grueso",
    "Empaste",
    "Corte americano",
    "Molduras y ornamentos",
  ],
  "Colocación de pisos y revestimientos": [
    "Cerámicos",
    "Porcelanato",
    "Parquet",
    "Vinílico",
    "Piedra natural",
    "Madera maciza",
  ],
  Impermeabilización: [
    "Techos y terrazas",
    "Muros húmedos",
    "Piletas",
    "Sótanos",
    "Losa de azotea",
  ],
  "Techista / Zinguería": [
    "Chapas",
    "Tejas",
    "Membrana asfáltica",
    "Pizarras",
    "Canaletas y bajadas",
    "Policarbonato",
  ],
  "Construcción en seco (Durlock)": [
    "Tabiques divisorios",
    "Cielorrasos",
    "Revestimientos",
    "Steel framing",
  ],
  Microcemento: ["Pisos", "Paredes", "Mesadas", "Mobiliario", "Exterior"],
  "Marmolería y piedra natural": [
    "Mármol",
    "Granito",
    "Cuarzo",
    "Travertino",
    "Mesadas",
    "Revestimientos",
  ],
  "Pulido de pisos": [
    "Madera",
    "Mármol",
    "Cemento alisado",
    "Porcelanato",
    "Microcemento",
  ],
  "Hormigón y estructuras": [
    "Hormigón armado",
    "Losas",
    "Columnas y vigas",
    "Fundaciones",
    "Hormigón visto",
  ],
  Demoliciones: [
    "Demolición parcial",
    "Demolición total",
    "Retiro de escombros",
    "Trabajo en altura",
  ],

  // Instalaciones
  Electricidad: [
    "Domiciliaria",
    "Industrial",
    "Comercial",
    "Obra nueva",
    "Mantenimiento",
    "Emergencias 24hs",
  ],
  Plomería: [
    "Domiciliaria",
    "Obras",
    "Emergencias 24hs",
    "Pozos y bombas",
    "Destapaciones",
  ],
  Gas: [
    "Instalaciones nuevas",
    "Servicio técnico",
    "Cambio de cañerías",
    "Gas envasado",
    "Conversión a gas natural",
  ],
  "Aire acondicionado y refrigeración": [
    "Split residencial",
    "Central",
    "VRV / VRF",
    "Cámaras frigoríficas",
    "Service y mantenimiento",
  ],
  Calefacción: [
    "Radiadores",
    "Losa radiante",
    "Caldera",
    "Estufa a gas",
    "Convectores",
  ],
  "Bombas de agua": [
    "Instalación",
    "Reparación",
    "Bombas sumergibles",
    "Presión constante",
    "Riego",
  ],
  "Sistemas de riego": [
    "Aspersores",
    "Goteo",
    "Automatización",
    "Jardines",
    "Espacios deportivos",
  ],
  "Instalación de cámaras de seguridad": [
    "CCTV analógico",
    "IP / HD",
    "DVR y NVR",
    "Alarmas",
    "Control de acceso",
  ],
  "Porteros eléctricos y automatismos": [
    "Portero eléctrico",
    "Videoportero",
    "Portón automático",
    "Barrera vehicular",
  ],
  "Paneles solares": [
    "Residencial on-grid",
    "Residencial off-grid",
    "Comercial",
    "Híbrido",
    "Monitoreo y mantenimiento",
  ],

  // Carpintería y Metal
  "Carpintería en madera": [
    "Muebles a medida",
    "Restauración",
    "Aberturas",
    "Deck y pergolados",
    "Ebanistería",
  ],
  "Fabricación de muebles a medida": [
    "Placard y vestidor",
    "Cocina",
    "Living y comedor",
    "Oficina",
    "Baño",
  ],
  "Carpintería metálica y herrería": [
    "Rejas y portones",
    "Escaleras metálicas",
    "Barandas",
    "Estructuras industriales",
    "Inox y aluminio",
  ],
  Soldadura: [
    "MIG / MAG",
    "TIG",
    "Electrodo",
    "Acero inoxidable",
    "Aluminio",
    "Soldadura estructural",
  ],
  Cerrajería: [
    "Instalación de cerraduras",
    "Apertura de emergencia",
    "Rejas y candados",
    "Cajas fuertes",
    "Duplicado de llaves",
  ],
  "Aberturas de aluminio y PVC": [
    "Ventanas corredizas",
    "Ventanas proyectantes",
    "Puertas y portones",
    "Doble vidrio hermético (DVH)",
    "Mosquiteros",
  ],
  Vidriería: [
    "Vidrio templado",
    "Espejos",
    "DVH",
    "Mamparas de baño",
    "Paños y puertas de vidrio",
  ],
  Tapicería: [
    "Tapizados de muebles",
    "Tapizados de autos",
    "Sillas y sillones",
    "Colchones y sommiers",
    "Cuero y eco-cuero",
  ],

  // Hogar y Mantenimiento
  "Limpieza del hogar": [
    "Limpieza regular",
    "Limpieza profunda",
    "Post-obra",
    "Limpieza de mudanza",
    "Fin de contrato",
  ],
  "Jardinería y paisajismo": [
    "Mantenimiento de jardín",
    "Diseño de jardines",
    "Podas y talas",
    "Plantas de interior",
    "Jardines verticales",
  ],
  "Fumigación y control de plagas": [
    "Cucarachas",
    "Ratas y ratones",
    "Termitas",
    "Mosquitos",
    "Chinches",
    "Hormigas",
  ],
  "Limpieza de tanques": [
    "Tanques de agua potable",
    "Cisternas",
    "Tanques de plástico",
    "Tanques de fibra",
  ],
  "Mantenimiento de piletas": [
    "Tratamiento de agua",
    "Limpieza y aspirado",
    "Reparación de filtraciones",
    "Construcción",
  ],
  Mudanzas: [
    "Residencial",
    "Comercial",
    "Embalaje profesional",
    "Guardamuebles",
    "Traslados largos",
  ],
  "Armado de muebles": [
    "Muebles flat-pack",
    "IKEA",
    "Placards",
    "Muebles de oficina",
    "Muebles de baño",
  ],
  "Pintura de interiores": [
    "Látex y pintura al agua",
    "Esmalte",
    "Empaste",
    "Pintura decorativa",
    "Texturas",
    "Cielorrasos",
  ],

  // Reparaciones
  "Service de electrodomésticos": [
    "Lavarropas",
    "Heladera",
    "Lavavajillas",
    "Microondas",
    "Televisores",
  ],
  "Reparación de lavarropas": [
    "Carga frontal",
    "Carga superior",
    "Secadora",
    "Lavasecarropas",
    "Marcas importadas",
  ],
  "Reparación de heladeras y freezers": [
    "Heladera familiar",
    "Freezer vertical",
    "Frigobar",
    "Refrigeración comercial",
    "No Frost",
  ],
  "Reparación de calefones y termotanques": [
    "Calefón a gas",
    "Calefón eléctrico",
    "Termotanque",
    "Caldera",
    "Sin llama piloto",
  ],
  "Reparación de cocinas y hornos": [
    "Horno a gas",
    "Horno eléctrico",
    "Hornallas y quemadores",
    "Cocina industrial",
    "Microondas convector",
  ],
  "Reparación de portones automáticos": [
    "Portón corredizo",
    "Portón seccional",
    "Barrera vehicular",
    "Automatización",
  ],
  "Reparación de persianas y cortinas": [
    "Persiana enrollable",
    "Cortina roller",
    "Cortina de tela",
    "Toldo retráctil",
    "Motor automatizado",
  ],

  // Exterior y Obras
  "Construcción de quinchos y pérgolas": [
    "Quincho de madera",
    "Quincho metálico",
    "Pérgola",
    "Galería cubierta",
    "Deck integrado",
  ],
  "Colocación de decks y pisos exteriores": [
    "Madera natural",
    "Madera sintética (WPC)",
    "Cerámico exterior",
    "Hormigón estampado",
  ],
  "Colocación de césped sintético": [
    "Residencial",
    "Deportivo",
    "Terraza y balcón",
    "Jardín vertical",
    "Canchas",
  ],
  "Parquización y movimiento de tierra": [
    "Nivelación y relleno",
    "Desmalezamiento",
    "Árboles y arbustos",
    "Parquización integral",
  ],
  "Construcción de piscinas": [
    "Hormigón proyectado",
    "Fibra de vidrio",
    "Prefabricada",
    "Infantil y jacuzzi",
    "Semi-enterrada",
  ],
  Pocero: [
    "Pozos de agua",
    "Pozos ciegos",
    "Perforaciones",
    "Zanjas y drenajes",
    "Fundaciones",
  ],
};

export function getSpecialtiesForTrade(tradeName: string): string[] {
  return TRADE_SPECIALTIES[tradeName] ?? [];
}
